import type { Product, LocalizedString, DemoOrder, DemoPayment } from "./types";

export const storageKeys = {
  searches: "kanoMart.searchHistory",
  vendors: "kanoMart.vendorRequests",
  cart: "kanoMart.cartCount",
  language: "kanoMart.language",
} as const;

// All keys are lowercase — use localizeCategory() to get display labels
export const categoryLabels: Record<string, LocalizedString> = {
  food: { en: "Food", ha: "Abinci" },
  fashion: { en: "Fashion", ha: "Kaya" },
  children: { en: "Children", ha: "Yara" },
  essentials: { en: "Essentials", ha: "Kayan yau da kullum" },
  "unmatched demand": { en: "Unmatched demand", ha: "Bukatar da ba a daidaita ba" },
};

export const products: Product[] = [
  {
    id: "food-rice",
    name: { en: "Kano local rice 10kg", ha: "Shinkafar Kano kilo 10" },
    category: { en: "Food", ha: "Abinci" },
    subcategory: { en: "Groceries", ha: "Kayan masarufi" },
    price: "NGN 18,500",
    vendor: "Dan Marke Stores",
    area: "Sabon Gari",
    availability: { en: "Available today", ha: "Akwai yau" },
    accent: "#176b4d",
    tags: ["rice", "shinkafa", "groceries", "kayan masarufi", "food", "abinci", "grain"],
  },
  {
    id: "food-tuwo",
    name: { en: "Tuwo and miyan kuka pack", ha: "Tuwo da miyan kuka" },
    category: { en: "Food", ha: "Abinci" },
    subcategory: { en: "Traditional dishes", ha: "Abincin gargajiya" },
    price: "NGN 2,800",
    vendor: "Hajiya Ladi Kitchen",
    area: "Tarauni",
    availability: { en: "Ready from 12pm", ha: "A shirye daga 12 na rana" },
    accent: "#b64232",
    tags: ["tuwo", "miyan kuka", "traditional", "abincin gargajiya", "restaurant", "gidajen abinci"],
  },
  {
    id: "food-snacks",
    name: { en: "Masa and spicy sauce", ha: "Masa da yaji" },
    category: { en: "Food", ha: "Abinci" },
    subcategory: { en: "Fast food and snacks", ha: "Kayan ciye-ciye" },
    price: "NGN 1,200",
    vendor: "Aminu Snacks",
    area: "Kofar Ruwa",
    availability: { en: "Fresh daily", ha: "Sabo kullum" },
    accent: "#d69b2d",
    tags: ["masa", "snacks", "fast food", "kayan ciye ciye", "yaji", "abinci"],
  },
  {
    id: "fashion-fabric",
    name: { en: "Ankara fabric bundle", ha: "Yadukan Ankara" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Fabrics", ha: "Yaduka" },
    price: "NGN 14,000",
    vendor: "Kantin Kwari Textiles",
    area: "Kantin Kwari",
    availability: { en: "New colors in stock", ha: "Sabbin launuka suna nan" },
    accent: "#5c4f83",
    tags: ["fabric", "fabrics", "yaduka", "ankara", "kaya", "textile", "fashion"],
  },
  {
    id: "fashion-jallabiya",
    name: { en: "Men jallabiya", ha: "Jallabiyar maza" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Jallabiya", ha: "Jallabiya" },
    price: "NGN 22,000",
    vendor: "Alhaji Musa Wears",
    area: "Fagge",
    availability: { en: "Sizes M to XXL", ha: "Girma M zuwa XXL" },
    accent: "#1f7b84",
    tags: ["jallabiya", "clothes", "boutique", "kayan boutique", "fashion", "kaya"],
  },
  {
    id: "fashion-perfume",
    name: { en: "Oil perfume set", ha: "Turaren mai" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Perfumes", ha: "Turare" },
    price: "NGN 6,500",
    vendor: "Rayyan Fragrance",
    area: "Zoo Road",
    availability: { en: "Top seller", ha: "Ana yawan saya" },
    accent: "#0f4b37",
    tags: ["perfume", "perfumes", "turare", "oil", "fragrance", "fashion", "kaya"],
  },
  {
    id: "fashion-shoes",
    name: { en: "Leather sandals", ha: "Takalman fata" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Shoes", ha: "Takalma" },
    price: "NGN 11,000",
    vendor: "Kano Footwear Hub",
    area: "Naibawa",
    availability: { en: "Made in Kano", ha: "An yi a Kano" },
    accent: "#854d2a",
    tags: ["shoes", "takalma", "sandals", "leather", "fashion", "kaya"],
  },
  {
    id: "fashion-boutique",
    name: { en: "Modest boutique gown", ha: "Rigar boutique" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Boutique clothes", ha: "Kayan boutique" },
    price: "NGN 17,500",
    vendor: "Amina Boutique",
    area: "Farm Centre",
    availability: { en: "New arrivals", ha: "Sabbin kaya sun iso" },
    accent: "#5c4f83",
    tags: ["boutique", "clothes", "kayan boutique", "gown", "riga", "fashion", "kaya"],
  },
  {
    id: "fashion-cosmetics",
    name: { en: "Cosmetics starter kit", ha: "Kayan kwalliya" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Cosmetics", ha: "Kayan kwalliya" },
    price: "NGN 8,700",
    vendor: "Safara Beauty",
    area: "Sheka",
    availability: { en: "Verified vendor", ha: "Tabbataccen dan kasuwa" },
    accent: "#b64232",
    tags: ["cosmetics", "makeup", "kwalliya", "kayan kwalliya", "beauty", "fashion", "kaya"],
  },
  {
    id: "fashion-caps",
    name: { en: "Embroidered northern cap", ha: "Hular zanna" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Caps", ha: "Huluna" },
    price: "NGN 4,500",
    vendor: "Huluna Kano",
    area: "Kofar Wambai",
    availability: { en: "Many patterns", ha: "Zane-zane da yawa" },
    accent: "#176b4d",
    tags: ["caps", "cap", "huluna", "hula", "zanna", "fashion", "kaya"],
  },
  {
    id: "fashion-watch",
    name: { en: "Everyday wristwatch", ha: "Agogon hannu" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Watches", ha: "Agogo" },
    price: "NGN 12,500",
    vendor: "Time House Kano",
    area: "Murtala Mohammed Way",
    availability: { en: "Warranty included", ha: "Akwai garanti" },
    accent: "#0f4b37",
    tags: ["watch", "watches", "agogo", "agogon hannu", "fashion", "kaya"],
  },
  {
    id: "fashion-glasses",
    name: { en: "Reading glasses", ha: "Tabarau" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Glasses", ha: "Tabarau" },
    price: "NGN 5,500",
    vendor: "Clear View Optics",
    area: "Dangi Roundabout",
    availability: { en: "Multiple strengths", ha: "Girma daban-daban" },
    accent: "#1f7b84",
    tags: ["glasses", "tabarau", "reading glasses", "fashion", "kaya"],
  },
  {
    id: "fashion-bag",
    name: { en: "Ladies handbag", ha: "Jakar hannu" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Bags", ha: "Jakunkuna" },
    price: "NGN 13,000",
    vendor: "Zahra Bags",
    area: "Aminu Kano Way",
    availability: { en: "Popular colors available", ha: "Akwai shahararrun launuka" },
    accent: "#854d2a",
    tags: ["bags", "bag", "jakunkuna", "jakar hannu", "handbag", "fashion", "kaya"],
  },
  {
    id: "fashion-jewelry",
    name: { en: "Jewelry set", ha: "Kayan ado" },
    category: { en: "Fashion", ha: "Kaya" },
    subcategory: { en: "Jewelry", ha: "Kayan ado" },
    price: "NGN 7,800",
    vendor: "Maryam Accessories",
    area: "Court Road",
    availability: { en: "Gift packs ready", ha: "Akwai kunshin kyauta" },
    accent: "#d69b2d",
    tags: ["jewelry", "jewellery", "kayan ado", "accessories", "fashion", "kaya"],
  },
  {
    id: "children-bag",
    name: { en: "Primary school bag", ha: "Jakar makarantar firamare" },
    category: { en: "Children", ha: "Yara" },
    subcategory: { en: "School bags", ha: "Jakunkunan makaranta" },
    price: "NGN 9,500",
    vendor: "Back To School Kano",
    area: "Hotoro",
    availability: { en: "Limited colors", ha: "Launuka kadan sun rage" },
    accent: "#2563eb",
    tags: ["school bag", "school bags", "jakar makaranta", "jakunkunan makaranta", "children", "yara"],
  },
  {
    id: "children-books",
    name: { en: "Exercise books pack", ha: "Kunshin littattafan rubutu" },
    category: { en: "Children", ha: "Yara" },
    subcategory: { en: "Books", ha: "Littattafai" },
    price: "NGN 3,200",
    vendor: "Bayero Bookshop",
    area: "Gwale",
    availability: { en: "Bulk prices available", ha: "Akwai farashin yawa" },
    accent: "#7c3aed",
    tags: ["books", "book", "littattafai", "exercise", "school", "education", "makaranta", "ilimi"],
  },
  {
    id: "children-lunch",
    name: { en: "Insulated lunch box", ha: "Akwatin abincin makaranta" },
    category: { en: "Children", ha: "Yara" },
    subcategory: { en: "Lunch box", ha: "Akwatin abincin makaranta" },
    price: "NGN 4,800",
    vendor: "Yara Essentials",
    area: "Nassarawa",
    availability: { en: "Available this week", ha: "Akwai a wannan mako" },
    accent: "#b64232",
    tags: ["lunch box", "akwatin abinci", "children", "school", "yara", "makaranta"],
  },
  {
    id: "children-education",
    name: { en: "After-school lesson booking", ha: "Rajistar karin karatu" },
    category: { en: "Children", ha: "Yara" },
    subcategory: { en: "Schools and education", ha: "Makarantu da ilimi" },
    price: "NGN 10,000",
    vendor: "Kano Learning Hub",
    area: "Bompai",
    availability: { en: "Weekday slots", ha: "Lokutan ranakun aiki" },
    accent: "#176b4d",
    tags: ["school", "schools", "education", "lesson", "makarantu", "ilimi", "karatu", "children", "yara"],
  },
  {
    id: "children-wears",
    name: { en: "Children native wear set", ha: "Kayan yara na gargajiya" },
    category: { en: "Children", ha: "Yara" },
    subcategory: { en: "Children wears", ha: "Kayan yara" },
    price: "NGN 12,000",
    vendor: "Little Kano Wears",
    area: "Sharada",
    availability: { en: "Ages 2 to 10", ha: "Shekara 2 zuwa 10" },
    accent: "#5c4f83",
    tags: ["children wears", "children clothes", "kayan yara", "native wear", "yara"],
  },
  {
    id: "children-shoes",
    name: { en: "Children school shoes", ha: "Takalman yara na makaranta" },
    category: { en: "Children", ha: "Yara" },
    subcategory: { en: "Children shoes", ha: "Takalman yara" },
    price: "NGN 8,200",
    vendor: "Yara Footwear",
    area: "Kawo",
    availability: { en: "Black and brown", ha: "Baki da ruwan kasa" },
    accent: "#1f7b84",
    tags: ["children shoes", "school shoes", "takalman yara", "shoes", "takalma", "yara", "makaranta"],
  },
];

export const demoOrders: DemoOrder[] = [
  {
    id: "KM-1042",
    item: { en: "Kano local rice 10kg", ha: "Shinkafar Kano kilo 10" },
    status: { en: "Ready for delivery", ha: "A shirye domin kaiwa" },
  },
  {
    id: "KM-1041",
    item: { en: "Ankara fabric bundle", ha: "Yadukan Ankara" },
    status: { en: "Vendor confirmed", ha: "Dan kasuwa ya tabbatar" },
  },
  {
    id: "KM-1040",
    item: { en: "Primary school bag", ha: "Jakar makarantar firamare" },
    status: { en: "Packed", ha: "An hada kaya" },
  },
];

export const demoPayments: DemoPayment[] = [
  {
    label: { en: "Card payment", ha: "Biyan kati" },
    value: { en: "Paid", ha: "An biya" },
  },
  {
    label: { en: "Bank transfer", ha: "Tura kudi ta banki" },
    value: { en: "Pending match", ha: "Ana jiran daidaitawa" },
  },
  {
    label: { en: "Pay on delivery", ha: "Biya idan an kawo" },
    value: { en: "Awaiting delivery", ha: "Ana jiran kai kaya" },
  },
];
